### ISSUE TITLE
Download Builder gives Error 502 

### ISSUE THREAD

**Issue by seanbw1609** [jquery/download.jqueryui.com#359]
Tried to download and got the download page : https://jqueryui.com/download/
Clicked the download button and then got a :
"Error 502 Ray ID: 50fe4a8e6c99ce3b • 2019-09-02 09:00:01 UTC
Bad gateway"

I can't get past this error.

**Comment by jacekjarzab** [comment]
same here, trying to download datepicker only and getting 502 cloudflare error instead

**Comment by checholin87** [comment]
same here, trying to download datepicker and progressbar and getting 502 cloudflare error instead

**Comment by jon-by** [comment]
same here, trying to download datepicker and getting 502 error.

**Comment by bansalakhil** [comment]
same here

**Comment by olhaborzenkova** [comment]
same here, trying to download widget + effects core and getting 502 error on click on download button

**Comment by jamescjchan** [comment]
Same here.
Error 502 Ray ID: 510aa73ed91fa3df • 2019-09-03 21:00:27 UTC
Bad gateway

**Comment by lang321** [comment]
same here

**Comment by Crisdvr** [comment]
Same here, any ETA on the fix?

**Comment by bfrazierr** [comment]
Getting the same error

**Comment by SILKIND** [comment]
getting the same error

**Comment by jaybee76** [comment]
Same problem here too, yesterday and still today.

Custom picker won't work (any changes and it defaults to a broken grey theme with none of the selected colours) and can't download any themes.

**Comment by erichstark** [comment]
Any updates?

**Comment by ljvillalba** [comment]
Same here, please help!

**Comment by tommyEllerhold** [comment]
Any updates today?

**Comment by milanvorel** [comment]
It is really shame, that some issue on the server prevents to use whole framework.
To developers @jzaefferer @mikeedwards @fnagel @scottgonzalez @dmethvin 
I appreciate your great work. Please give us some feedback, at least. Thanks.

**Comment by scottgonzalez** [comment]
Please do not pint individual developers. Anyone that will actually work on this should already be watching the repo. Many of the people you are pinging aren't involved anymore.

**Comment by jamescjchan** [comment]
Thanks, @scottgonzalez . At least we know this issue is being monitored. 👍

**Comment by scottgonzalez** [comment]
Only because I was pinged. I am no longer involved with this project.

**Comment by VAshkevron71** [comment]
Been down for a few days now.

**Comment by mattchatterley** [comment]
Still seems to have the same problem - just trying to download a default package..

**Comment by avihenri** [comment]
The issue is still happening, I get a 502.. think I might have to go elsewhere as it has been over a week. Shame!

**Comment by cdp1337** [comment]
It's *still* offline.  Is jQueryUI finally being abandoned after all these years?

**Comment by EtienneDelepine** [comment]
Same here

Error 502 Ray ID: 5141d82d1c41cd93 • 2019-09-10 13:45:48 UTC
Bad gateway
download.jqueryui.com Host Error

**Comment by THemming** [comment]
I had to resort to cloning this repo and running the download server on localhost. I was able to generate a custom build from this.

**Comment by cdp1337** [comment]
> I had to resort to cloning this repo and running the download server on localhost. I was able to generate a custom build from this.

Awesome!  Good to know cloning locally still works.  I ended up building a custom implementation for the task I needed complete since their servers have been offline for over a week, but I'll remember that for my next project.

**Comment by mattyd2017** [comment]
well thats a bit of a pain and theres no real alternatives looked at the other ones come on boys we need it back up

**Comment by mattyd2017** [comment]
> 
> 
> I had to resort to cloning this repo and running the download server on localhost. I was able to generate a custom build from this.

how did you do that

**Comment by THemming** [comment]
> > I had to resort to cloning this repo and running the download server on localhost. I was able to generate a custom build from this.
> 
> how did you do that

I followed the instructions in the [README](https://github.com/jquery/download.jqueryui.com/blob/master/README.md).

Worked with the following installed (`brew install libpng imagemagick node@10`):

- Node 10
- imagemagick 7
- libpng

I cloned this Git repo then ran:

```
npm install -g grunt-cli
npm install
grunt prepare
node server.js --console
```

This started the localhost server, which I used to generate the custom bundle.

**Comment by mattyd2017** [comment]
> 
> 
> > > I had to resort to cloning this repo and running the download server on localhost. I was able to generate a custom build from this.
> > 
> > 
> > how did you do that
> 
> I followed the instructions in the [README](https://github.com/jquery/download.jqueryui.com/blob/master/README.md).
> 
> Worked with the following installed (`brew install libpng imagemagick node@10`):
> 
>     * Node 10
> 
>     * imagemagick 7
> 
>     * libpng
> 
> 
> I cloned this Git repo then ran:
> 
> ```
> npm install -g grunt-cli
> npm install
> grunt prepare
> node server.js --console
> ```
> 
> This started the localhost server, which I used to generate the custom bundle.

looks way to complicated for me that

**Comment by mattyd2017** [comment]
> 
> 
> > > > I had to resort to cloning this repo and running the download server on localhost. I was able to generate a custom build from this.
> > > 
> > > 
> > > how did you do that
> > 
> > 
> > I followed the instructions in the [README](https://github.com/jquery/download.jqueryui.com/blob/master/README.md).
> > Worked with the following installed (`brew install libpng imagemagick node@10`):
> > ```
> > * Node 10
> > 
> > * imagemagick 7
> > 
> > * libpng
> > ```
> > 
> > 
> > I cloned this Git repo then ran:
> > ```
> > npm install -g grunt-cli
> > npm install
> > grunt prepare
> > node server.js --console
> > ```
> > 
> > 
> > This started the localhost server, which I used to generate the custom bundle.
> 
> looks way to complicated for me that

done it noe cheers mate

**Comment by mattyd2017** [comment]
cant get it to work npm errors

**Comment by nikolas** [comment]
This issue was brought up in #jquery on irc just now. Who's responsible for this repo? Add me to maintainers if you need help :P

**Comment by sareliande** [comment]
I'm having the same issues listed above - the elements on the themeroller page are not being updated, and go grey after entering in any changes to the default settings/colors/fields. When trying to download I'm getting the 502 Bad Gateway error: Ray ID: 514b7ccd782ab9fe • 2019-09-11 17:51:03 UTC

When on the themeroller page, I checked the errors under the console and I've attached the screenshot of them.
![Jquery Errors](https://user-images.githubusercontent.com/34250978/64721918-746f9580-d49b-11e9-8104-50090419b505.PNG)

**Comment by mattyd2017** [comment]
just needed the datpicker and found the js and css for that took me ages but had to find it off an old website i did and that works for me tried to local host the ui site but absolutely no way could i get that to talk and prob gave myself a virus trying loads of different solutions trying to get that to work

**Comment by milanvorel** [comment]
Probably no one from the jquery community follows this ticket. There is no feedback from anyone involved.
Is there any other way how to contact someone from jquery UI?
It seems to be abandoned with no help.
The only way is make a clone and run it somewhere else. But I'm not capable to do it.

**Comment by mattyd2017** [comment]
> 
> 
> Probably no one from the jquery community follows this ticket. There is no feedback from anyone involved.
> Is there any other way how to contact someone from jquery UI?
> It seems to be abandoned with no help.
> The only way is make a clone and run it somewhere else. But I'm not capable to do it.

think jquerys coming to an end prob why no ones bothered to sort it out

**Comment by nikolas** [comment]
@milanvorel you could contact the JS foundation: https://js.foundation/contact (new name of the jQuery foundation)

**Comment by yonder83** [comment]
Same here

**Comment by John-Kjoller** [comment]
Same here

**Comment by nikolas** [comment]
For now you can just download jQuery UI through CDNs like google: https://developers.google.com/speed/libraries/#jquery-ui

**Comment by lukasbableck** [comment]
You can use my download server to build jqueryUI.

http://templersmc.net:8888/download

**Comment by syousef1975** [comment]
> You can use my download server to build jqueryUI.
> ((done, new link: https://jqueryui.templersmc.net/download ))

502 Bad Gateway
nginx/1.14.2

You managed to replicate their error! ;-)

But seriously  thanks for trying to provide something.

**Comment by timhj** [comment]
> You can use my download server to build jqueryUI.
> 
> http://templersmc.net:8888/download
> (adding SSL support and moving it to a subdomain later this day)
> ((done, new link: https://jqueryui.templersmc.net/download ))

Legend.

**Comment by mgol** [comment]
This should work now.

**Comment by adumesny** [comment]
@THemming thank you for the info!
I was able to serve locally on windows (well Ubuntu VM as packages are not win32 compatible) using https://docs.microsoft.com/en-us/windows/wsl/install-win10

then in Ubuntu :
```
sudo apt install imagemagick-6.q16
# install nodejs
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
# might have done libpng but brew gave be issues if I recall
brew install libpng
```

Then I mod `config.json` to just have 1.12.1 entries (the last gave error and I didn't need)
and followed your steps otherwise. Hope this helps someone else...

**Comment by pluracoin** [comment]
2020 and the problem still persist. Is jqueryui abandoned?

**Comment by jjsibborn** [comment]
Commenting here to get notification in when/if themeroller gets fixed (due to other ticket thread was closed)

At present, themeroller is still broken. Is there an ETA on fixing it? Or is it even being looked at?

**Comment by fnagel** [comment]
> Is there an ETA on fixing it? Or is it even being looked at?

Take a look here please #390

**Comment by atlasjon** [comment]
Quoted from #390: 
> jQueryUI is an OpenJS Foundation Emeritus Project.  Emeritus projects are those which the maintainers feel have reached or are nearing end-of-life.

What are folks using as an alternative to jQueryUI?

**Comment by Nadeem2462** [comment]
Got "Error 502 Ray ID: 574c92544b7fc601 • 2020-03-16 06:55:58 UTC
Bad gateway" when try to download custom jqueryui package.

**Comment by TheRealMikeD** [comment]
Got this just now:
Error 502 Ray ID: 57a3dd570fb0eb49 • 2020-03-26 21:11:31 UTC
Bad gateway

**Comment by msandi** [comment]
> I'm getting the 502 error now (and very early this morning too)
> 
> Tried to download and got the download page : https://jqueryui.com/download/
> Clicked the download button and then got a :
> "Error 502 Ray ID: 50fe4a8e6c99ce3b • 2019-09-02 09:00:01 UTC
> Bad gateway"
> 
> I can't get past this error.

**Comment by jjsibborn** [comment]
As this has taken far too long, the solution for us is to redevelop our software to not include jquery-ui.
Shame really.

**Comment by airplanenoise** [comment]
+1, reported on a another bug and told to follow here. seems like this in in EOL... Shame cause I only need one aspect of the library.

**Comment by mircea-de-arges** [comment]
Looking forward to the fix of this download page.
Error 502 Ray ID: 5886a5f82e1efd01 • 2020-04-23 09:44:51 UTC
Bad gateway

**Comment by APerricone** [comment]
is a fix planned?

**Comment by as1414** [comment]
Still doing it... why not announce EOL on the website if that's what it is?  Are we missing something?

**Comment by anhaabaete** [comment]
Still Doing  Error 502 Ray ID: 58f4a616ed49f5ff • 2020-05-06 18:08:49 UTC

**Comment by MrD0llaro** [comment]
:(

**Comment by theJamel** [comment]
> 
> 
> You can use my download server to build jqueryUI.
> 
> http://templersmc.net:8888/download
> (adding SSL support and moving it to a subdomain later this day)
> ((done, new link: https://jqueryui.templersmc.net/download ))

Getting a 404 unfortunately.
Any plans on making your downloader available again?

**Comment by lukasbableck** [comment]
> > You can use my download server to build jqueryUI.
> > http://templersmc.net:8888/download
> > (adding SSL support and moving it to a subdomain later this day)
> > ((done, new link: https://jqueryui.templersmc.net/download ))
> 
> Getting a 404 unfortunately.
> Any plans on making your downloader available again?

I'll work on it today. 😉

**Comment by lukasbableck** [comment]
My mirror is back online. 
https://jqueryui.templersmc.net/download

**Comment by fabiofaleiros** [comment]
> My mirror is back online.
> https://jqueryui.templersmc.net/
> 
> It might take a while for you until the DNS record is active and you can access it.

Tks a lot!

**Comment by keeganrowe** [comment]
> My mirror is back online.
> https://jqueryui.templersmc.net/
> 
> It might take a while for you until the DNS record is active and you can access it.

Thanks for the mirror, however when I try to download something just now, after ~60 seconds I receive: Error 504 Ray ID: 592108589c58fd2a • 2020-05-12 03:25:28 UTC Gateway time-out

Is it too busy?

**Comment by adamcollingburn** [comment]
The fact that this has been down for a little over **8 months now**, is a little bit of a joke.

**Comment by foofiequaf** [comment]
You've got to be kidding me.... I see that no one seems to be able to download a custom Jquery-UI build since sept. of 2019.... that is ridiculous.... I simply want tooltips.  Any way to get that without having to clone the repository etc.

**Comment by lukasbableck** [comment]
> You've got to be kidding me.... I see that no one seems to be able to download a custom Jquery-UI build since sept. of 2019.... that is ridiculous.... I simply want tooltips. Any way to get that without having to clone the repository etc.

Well you can use my mirror of the download page at https://jqueryui.templersmc.net

**Comment by jjsibborn** [comment]
> > You've got to be kidding me.... I see that no one seems to be able to download a custom Jquery-UI build since sept. of 2019.... that is ridiculous.... I simply want tooltips. Any way to get that without having to clone the repository etc.
> 
> Well you can use my mirror of the download page at https://jqueryui.templersmc.net

Unfortunately I have not been able to use your link since you posted it previously.  Whenever I used it to create a custom themeroller, and download the jquery (I need 1.10.4) I get an error 504 Gateway Timed Out

The only way we found around this is to redevelop our website to not use the themeroller at all, and customise it all ourselves, as it it taking far too long to fix.

**Comment by lukasbableck** [comment]
Oh, 1.10.4 indeed doesn't work on my site. I might be able to fix it.

**Comment by bounlu** [comment]
same here, can't download

**Comment by Mckill3r** [comment]
> 
> 
> > You've got to be kidding me.... I see that no one seems to be able to download a custom Jquery-UI build since sept. of 2019.... that is ridiculous.... I simply want tooltips. Any way to get that without having to clone the repository etc.
> 
> Well you can use my mirror of the download page at https://jqueryui.templersmc.net

Thanks bro !

**Comment by astehlik** [comment]
> Oh, 1.10.4 indeed doesn't work on my site. I might be able to fix it.

@lukasbableck I fixed the download for 1.10 and 1.11 in our [Docker image](https://hub.docker.com/r/intera/jquery-ui).

You can check out [the patch here](https://github.com/Intera/docker-jquery-ui/blob/master/patches/fix-basename-calls.diff)

I hope it helps :)

**Comment by foofiequaf** [comment]
Thanks,  I've worked around things for now but when/if I get a chance I will try that.

**Comment by lukasbableck** [comment]
> > Oh, 1.10.4 indeed doesn't work on my site. I might be able to fix it.
> 
> @lukasbableck I fixed the download for 1.10 and 1.11 in our [Docker image](https://hub.docker.com/r/intera/jquery-ui).
> 
> You can check out [the patch here](https://github.com/Intera/docker-jquery-ui/blob/master/patches/fix-basename-calls.diff)
> 
> I hope it helps :)

Thank you very much.

I just applied those patches on my mirror.
1.10 and 1.11 are now working.

cc @jjsibborn

**Comment by jjsibborn** [comment]
> > > Oh, 1.10.4 indeed doesn't work on my site. I might be able to fix it.
> > 
> > 
> > @lukasbableck I fixed the download for 1.10 and 1.11 in our [Docker image](https://hub.docker.com/r/intera/jquery-ui).
> > You can check out [the patch here](https://github.com/Intera/docker-jquery-ui/blob/master/patches/fix-basename-calls.diff)
> > I hope it helps :)
> 
> Thank you very much.
> 
> I just applied those patches on my mirror.
> 1.10 and 1.11 are now working.
> 
> cc @jjsibborn

Thank you @lukasbableck for the update and also @foofiequaf for fixing it.

I have also gone and worked around the whole jquery themeroller, but atleast it can be used as a backup, very much appreciated.
I dont understand how it can be fixed so quickly by the community, yet the official themeroller has not been fixed in nearly 9months.

**Comment by fabulousJavaScripter** [comment]
Guys, how fast such problems supposedly to be resolved?

**Comment by uchuugaka** [comment]
Ok, what needs to be done here?

**Comment by jlferrete** [comment]
Same. Tried to download and got the download page : https://jqueryui.com/download/
Clicked the download button and then got a :
"Error 502 Ray ID: 50fe4a8e6c99ce3b • 2019-09-02 09:00:01 UTC
Bad gateway"

**Comment by Mckill3r** [comment]
> 
> 
> Same. Tried to download and got the download page : https://jqueryui.com/download/
> Clicked the download button and then got a :
> "Error 502 Ray ID: 50fe4a8e6c99ce3b • 2019-09-02 09:00:01 UTC
> Bad gateway"

Use that : https://jqueryui.templersmc.net/download/#!version=1.12.1

**Comment by showkatalisalim** [comment]
Those who tried to download jqueryui and failed,  just  send me an email to showkatalisalim@yahoo.com

I have downloaded jqueriy-ui-1.12.1 as well s jquery mobile, jquery theme.. just email me.

**Comment by showkatalisalim** [comment]
I downloaded few days ago. can download it from my google drive:

https://drive.google.com/drive/folders/13SGHQ1SfUjchvusyT-XUNiKyzwQAjHac?usp=sharing

**Comment by beccastatic** [comment]
is anyone even trying to fix this?!? being down since September 2019 seems a way too long of time to be down

**Comment by uchuugaka** [comment]
Who has access to it?

**Comment by mpoirier101** [comment]
What is going on with this ?!?
Anybody has a workaround ?
How can we get a custom download ?

**Comment by Mckill3r** [comment]
> 
> 
> @fnagel what is going on with this ?!?
> Anybody has a workaround ?
> How can we get a custom download ?

Here is your workaround : https://jqueryui.templersmc.net/download/#!version=1.12.1

**Comment by mpoirier101** [comment]
> > @fnagel what is going on with this ?!?
> > Anybody has a workaround ?
> > How can we get a custom download ?
> 
> Here is your workaround : https://jqueryui.templersmc.net/download/#!version=1.12.1

Perfect ! Thanks !

**Comment by uchuugaka** [comment]
Workarounds are fine but how do we get the real thing back to health?

**Comment by mpoirier101** [comment]
From the state of things, I finally decided to create my own simple no-non-sense dialog...

**Comment by skachkov** [comment]
hi folks!
https://jqueryui.com/download/ throes 502 cloudflare error

same for:
https://api.jqueryui.com/datepicker/
https://api.jqueryui.com/category/utilities/

**Comment by mattyd2017** [comment]
think only thing you can do in this case is find the script files by downloading the entire jqury library and just importing it into ya web page or use a cdn its not coming back been months now and i'll be honest does anyone use it anymore but you can get it on npm and package manager so might be as well to get it via npm and save the package

**Comment by miclgael** [comment]
+1 for what its worth. _*sigh_

**Comment by LukeTOBrien** [comment]
This has been an issue for many months now, it really damages the reputation of jQuery and the wider jQuery foudation and is an embarrisment.  
Everyone can see this error and everyone can see the issues on GitHub build up and up, someone please sort this.

@timmywil is the jQuery core team lead, so hope he can find someone to sort this out.

**Comment by timmywil** [comment]
You're right. I'd love to see the download builder fixed. As someone who's rarely worked on UI stuff before, I am not familiar with how the download builder works. jQuery resources are very limited these days, and most of the UI team is not around anymore. That said, there a few people that can still take a look, and I hope they can soon.

**Comment by LukeTOBrien** [comment]
Perhaps I tagged in the wrong guy, but do you know someone who could help?  
I'm just going by Insights, @scottgonzalez is the most recent contributor on the jQuery UI project.

**Comment by birdsaloon** [comment]
Looks like there is opportunity for another company to take over.  Obvious the developers of this one don't care ... I will keep looking for another way to get the latest download.  Sad that they have not responded to this feed in so long.  Put my development on hold until I can find another solution like it.

**Comment by astehlik** [comment]
@birdsaloon There are already some solutions out there.

You can check out https://jqueryui.templersmc.net/ by @lukasbableck for a running version.

Or you can use our docker image: https://hub.docker.com/r/intera/jquery-ui.

**Comment by mpoirier101** [comment]
Don't know about you guys but I moved my development to W3School JS and CSS tools. Obviously not all the bells and whistles of jQueryUI... but do we really need all this ? I like the simplicity and efficiency of these very small librairies. This and some simple Web Components I developed is all I need !

https://www.w3schools.com/w3css/w3css_references.asp
https://www.w3schools.com/w3js/w3js_references.asp

**Comment by LukeTOBrien** [comment]
I never knew about the W3js and css, thanks for sharing!
I use jQuery UI for draggable/droppable and other effects - I can't find
any easy to use alternatives for drag/drop.

Yes there are workarounds, but if you are writing a blog or tutorial then
you want to link to to official download, and it's it gives a 500 error all
the time it just doesn't look good.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mpoirier101** [comment]
I have built a moveable dialog from code found on w3school. It's available here: https://github.com/mpoirier101/mpComponents

Maybe you can get inspiration for your own draggable component...

**Comment by LukeTOBrien** [comment]
Thanks!!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by klw123** [comment]
> > @fnagel what is going on with this ?!?
> > Anybody has a workaround ?
> > How can we get a custom download ?
> 
> Here is your workaround : https://jqueryui.templersmc.net/download/#!version=1.12.1

Thank you! You are a good boy

**Comment by mpoirier101** [comment]
In case you missed it: https://www.w3schools.com/howto/howto_js_draggable.asp

**Comment by uchuugaka** [comment]
Does not do much for date pickers. jQuery has that better than anybody.

**Comment by mpoirier101** [comment]
date pickers are now an integral part of HTML 5 !

*Michel Poirier*
Développeur logiciel
Sainte-Agathe-des-Monts, QC
[image: LinkedIn]
<http://ca.linkedin.com/in/michelpoirier101>

**Comment by uchuugaka** [comment]
Oh yes they are in the spec and come featureless and useless.
Tag name only almost.

>

**Comment by victorsioson** [comment]
I used npm i jquery-ui it works now

**Comment by AnthonyVO** [comment]
Downloading from the ThemeRoller or just hitting https://download.jqueryui.com/download still fails with 502.

**Comment by AnthonyVO** [comment]
> This has been an issue for many months now, it really damages the reputation of jQuery and the wider jQuery foudation and is an embarrisment.

Since Sept 2, 2019 !!!    If your looking to drive a stake into the heart of a project then blocking downloads is a sure way to accomplish that.

**Comment by uchuugaka** [comment]
Clearly it is time for a fork or something.

**Comment by F-WP** [comment]
It is still giving the 502, and if I want to sign in, or if I want to sign up for a new Account, I'm always forwarded to https://accounts.zoho.com/signin?servicename=ZohoDiscussions&serviceurl=https%3A%2F%2Fforum.jquery.com&hide_signup=true
Or
https://www.zohodiscussions.com/register?serviceurl=%2FforumHome.do%3FforumGroupURL%3Djquery%26referrer%3DsignUp%26forumGroupId%3D14737000000003003&referrer=signUp&forumGroupId=14737000000003003

It seems they no longer want to get new users or have the old users a good Experimente.

**Comment by fnagel** [comment]
@F-WP Zoho is more or less dead, please use our Slack channel: https://jqueryui-dev.slack.com/

**Comment by mpoirier101** [comment]
Finally removed all traces of jQuery, jQueryUI and datatable plugin. Building pure js replacement was very satisfying!

**Comment by GoodPie** [comment]
Looks like the issue is still occurring. Any updates on this?

**Comment by uchuugaka** [comment]
Seems like they just gave up on it.

**Comment by fnagel** [comment]
@GoodPie @uchuugaka We are working on the issue but have very limited resources and complex issues with our build infrastructure. Sorry for the inconvenience :-/

**Comment by dmethvin** [comment]
If someone would like to help with maintaining and fixing the infrastructure let us know.

**Comment by mmalferov** [comment]
> @GoodPie @uchuugaka Мы работаем над этой проблемой, но у нас очень ограниченные ресурсы и сложные проблемы с нашей инфраструктурой сборки. Приносим извинения за неудобства :-/

Никому не нужны причины и извинения. Разработчикам нужен рабочий вариант: ссылка на ресурс, на котором можно загрузить необходимые модули.

**Comment by chyvak1831** [comment]
ahaha, guys check it out - this russian men saying that "no needs sorry - you **MUST** to fix it"
https://github.com/jquery/download.jqueryui.com/issues/359#issuecomment-672988446

**Comment by chyvak1831** [comment]
> > @GoodPie @uchuugaka Мы работаем над этой проблемой, но у нас очень ограниченные ресурсы и сложные проблемы с нашей инфраструктурой сборки. Приносим извинения за неудобства :-/
> 
> Никому не нужны причины и извинения. Разработчикам нужен рабочий вариант: ссылка на ресурс, на котором можно загрузить необходимые модули.

що кацапюра, всі повинні тебе послухатися? йди нахєр звідси у свій мухосранськ

**Comment by mmalferov** [comment]
> ahaha, guys check it out - this russian men saying that "no needs sorry - you **MUST** to fix it"
> [#359 (comment)](https://github.com/jquery/download.jqueryui.com/issues/359#issuecomment-672988446)

'MUST' !== 'NEED'

**Comment by LukeTOBrien** [comment]
@chyvak1831 We must show respect to our fellow developers - The team have responded and we know that they are dealing with it.  
All open-source projects rely on contributors who volunteer their time, anyone can decide to volunteer their time.

**Comment by amirjj** [comment]
same problem here, but I see developers are working on it. cheers

**Comment by mpalladinru** [comment]
So, it's not working for almost a YEAR? Seriously?

**Comment by timmywil** [comment]
Locking this ticket to maintainers for now. We don't have the same resources for UI that we used to. That said, @mgol and others have picked up the mantle and we have a fix that we are testing.

**Comment by fnagel** [comment]
Hey everyone! If you would like to help, test this PR and give some feedback: https://github.com/jquery/download.jqueryui.com/pull/552

**Comment by mgol** [comment]
Hey, I've just merged my PR #552 & I deployed it; it has a chance to fix those 502 errors. Now, I don't want to give any guarantees since last time I thought it was fixed it broke within an hour but for now it seems to work. Please test & report issues if you find something is still broken.

I'm going to close this issue as we already have #390 to track this.
